### ISSUE TITLE
Add brains to Prisma schema and API

### ISSUE THREAD

**Issue by hdavidethan** [SciQuel/SciQuel#20]
Create a new model on the Prisma schema for brains. It should have a similar interface as the existing PageViews

Add API endpoint for brains, similar to page_views as well

**Comment by yeshengliu** [comment]
@hdavidethan What would be the use cases for brains, just wondering?

**Comment by edwrd-chen** [comment]
@yeshengliu Brains are to indicate someone learned something from an article. But really, because we won't strictly tell someone what brains are, you can also think of them as our site's version of "likes."
